server:
    port: 8084


spring:
  application:
    name: APIGATEWAY

  config:
    import: configserver:http://localhost:8888/


  cloud:
    gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE
        predicates:
            - Path=/users/**

      - id: HOTELSERVICE
        uri: lb://HOTELSERVICE
        predicates:
            - Path=/hotels/**

      - id: RATINGSERVICE
        uri: lb://RATINGSERVICE
        predicates:
            - Path=/ratings/**      

  